// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: telemetry.proto

package telemetrypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Severity      string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"` // DEBUG, INFO, WARN, ERROR
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`     // component name
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,6,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *LogEntry) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *LogEntry) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *LogEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type MetricEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Value         float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricEntry) Reset() {
	*x = MetricEntry{}
	mi := &file_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricEntry) ProtoMessage() {}

func (x *MetricEntry) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricEntry.ProtoReflect.Descriptor instead.
func (*MetricEntry) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *MetricEntry) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *MetricEntry) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *MetricEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricEntry) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricEntry) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *MetricEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type EventEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "test_started", "test_completed", "driver_loaded", etc.
	Payload       string                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                      // JSON-encoded event data
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventEntry) Reset() {
	*x = EventEntry{}
	mi := &file_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEntry) ProtoMessage() {}

func (x *EventEntry) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEntry.ProtoReflect.Descriptor instead.
func (*EventEntry) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *EventEntry) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *EventEntry) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *EventEntry) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventEntry) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *EventEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type StreamAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceivedCount int64                  `protobuf:"varint,1,opt,name=received_count,json=receivedCount,proto3" json:"received_count,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAck) Reset() {
	*x = StreamAck{}
	mi := &file_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAck) ProtoMessage() {}

func (x *StreamAck) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAck.ProtoReflect.Descriptor instead.
func (*StreamAck) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *StreamAck) GetReceivedCount() int64 {
	if x != nil {
		return x.ReceivedCount
	}
	return 0
}

func (x *StreamAck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_telemetry_proto protoreflect.FileDescriptor

const file_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x0ftelemetry.proto\x12\x10dvf.telemetry.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbd\x02\n" +
	"\bLogEntry\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12>\n" +
	"\x06fields\x18\x06 \x03(\v2&.dvf.telemetry.v1.LogEntry.FieldsEntryR\x06fields\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9f\x02\n" +
	"\vMetricEntry\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\x12A\n" +
	"\x06labels\x18\x05 \x03(\v2).dvf.telemetry.v1.MetricEntry.LabelsEntryR\x06labels\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaf\x01\n" +
	"\n" +
	"EventEntry\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x18\n" +
	"\apayload\x18\x04 \x01(\tR\apayload\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"J\n" +
	"\tStreamAck\x12%\n" +
	"\x0ereceived_count\x18\x01 \x01(\x03R\rreceivedCount\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\xf7\x01\n" +
	"\x10TelemetryService\x12G\n" +
	"\n" +
	"StreamLogs\x12\x1a.dvf.telemetry.v1.LogEntry\x1a\x1b.dvf.telemetry.v1.StreamAck(\x01\x12M\n" +
	"\rStreamMetrics\x12\x1d.dvf.telemetry.v1.MetricEntry\x1a\x1b.dvf.telemetry.v1.StreamAck(\x01\x12K\n" +
	"\fStreamEvents\x12\x1c.dvf.telemetry.v1.EventEntry\x1a\x1b.dvf.telemetry.v1.StreamAck(\x01BUZSgithub.com/kartheekbudime/driver-validation-suite/go-orchestrator/proto/telemetrypbb\x06proto3"

var (
	file_telemetry_proto_rawDescOnce sync.Once
	file_telemetry_proto_rawDescData []byte
)

func file_telemetry_proto_rawDescGZIP() []byte {
	file_telemetry_proto_rawDescOnce.Do(func() {
		file_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)))
	})
	return file_telemetry_proto_rawDescData
}

var file_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_telemetry_proto_goTypes = []any{
	(*LogEntry)(nil),              // 0: dvf.telemetry.v1.LogEntry
	(*MetricEntry)(nil),           // 1: dvf.telemetry.v1.MetricEntry
	(*EventEntry)(nil),            // 2: dvf.telemetry.v1.EventEntry
	(*StreamAck)(nil),             // 3: dvf.telemetry.v1.StreamAck
	nil,                           // 4: dvf.telemetry.v1.LogEntry.FieldsEntry
	nil,                           // 5: dvf.telemetry.v1.MetricEntry.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_telemetry_proto_depIdxs = []int32{
	4, // 0: dvf.telemetry.v1.LogEntry.fields:type_name -> dvf.telemetry.v1.LogEntry.FieldsEntry
	6, // 1: dvf.telemetry.v1.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	5, // 2: dvf.telemetry.v1.MetricEntry.labels:type_name -> dvf.telemetry.v1.MetricEntry.LabelsEntry
	6, // 3: dvf.telemetry.v1.MetricEntry.timestamp:type_name -> google.protobuf.Timestamp
	6, // 4: dvf.telemetry.v1.EventEntry.timestamp:type_name -> google.protobuf.Timestamp
	0, // 5: dvf.telemetry.v1.TelemetryService.StreamLogs:input_type -> dvf.telemetry.v1.LogEntry
	1, // 6: dvf.telemetry.v1.TelemetryService.StreamMetrics:input_type -> dvf.telemetry.v1.MetricEntry
	2, // 7: dvf.telemetry.v1.TelemetryService.StreamEvents:input_type -> dvf.telemetry.v1.EventEntry
	3, // 8: dvf.telemetry.v1.TelemetryService.StreamLogs:output_type -> dvf.telemetry.v1.StreamAck
	3, // 9: dvf.telemetry.v1.TelemetryService.StreamMetrics:output_type -> dvf.telemetry.v1.StreamAck
	3, // 10: dvf.telemetry.v1.TelemetryService.StreamEvents:output_type -> dvf.telemetry.v1.StreamAck
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_telemetry_proto_init() }
func file_telemetry_proto_init() {
	if File_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_telemetry_proto_goTypes,
		DependencyIndexes: file_telemetry_proto_depIdxs,
		MessageInfos:      file_telemetry_proto_msgTypes,
	}.Build()
	File_telemetry_proto = out.File
	file_telemetry_proto_goTypes = nil
	file_telemetry_proto_depIdxs = nil
}
