// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: orchestrator.proto

package orchestratorpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestRunStatus int32

const (
	TestRunStatus_TEST_RUN_STATUS_UNSPECIFIED TestRunStatus = 0
	TestRunStatus_TEST_RUN_STATUS_PENDING     TestRunStatus = 1
	TestRunStatus_TEST_RUN_STATUS_QUEUED      TestRunStatus = 2
	TestRunStatus_TEST_RUN_STATUS_RUNNING     TestRunStatus = 3
	TestRunStatus_TEST_RUN_STATUS_PASSED      TestRunStatus = 4
	TestRunStatus_TEST_RUN_STATUS_FAILED      TestRunStatus = 5
	TestRunStatus_TEST_RUN_STATUS_ERRORED     TestRunStatus = 6
	TestRunStatus_TEST_RUN_STATUS_CANCELLED   TestRunStatus = 7
	TestRunStatus_TEST_RUN_STATUS_TIMEOUT     TestRunStatus = 8
)

// Enum value maps for TestRunStatus.
var (
	TestRunStatus_name = map[int32]string{
		0: "TEST_RUN_STATUS_UNSPECIFIED",
		1: "TEST_RUN_STATUS_PENDING",
		2: "TEST_RUN_STATUS_QUEUED",
		3: "TEST_RUN_STATUS_RUNNING",
		4: "TEST_RUN_STATUS_PASSED",
		5: "TEST_RUN_STATUS_FAILED",
		6: "TEST_RUN_STATUS_ERRORED",
		7: "TEST_RUN_STATUS_CANCELLED",
		8: "TEST_RUN_STATUS_TIMEOUT",
	}
	TestRunStatus_value = map[string]int32{
		"TEST_RUN_STATUS_UNSPECIFIED": 0,
		"TEST_RUN_STATUS_PENDING":     1,
		"TEST_RUN_STATUS_QUEUED":      2,
		"TEST_RUN_STATUS_RUNNING":     3,
		"TEST_RUN_STATUS_PASSED":      4,
		"TEST_RUN_STATUS_FAILED":      5,
		"TEST_RUN_STATUS_ERRORED":     6,
		"TEST_RUN_STATUS_CANCELLED":   7,
		"TEST_RUN_STATUS_TIMEOUT":     8,
	}
)

func (x TestRunStatus) Enum() *TestRunStatus {
	p := new(TestRunStatus)
	*p = x
	return p
}

func (x TestRunStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestRunStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_orchestrator_proto_enumTypes[0].Descriptor()
}

func (TestRunStatus) Type() protoreflect.EnumType {
	return &file_orchestrator_proto_enumTypes[0]
}

func (x TestRunStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TestRunStatus.Descriptor instead.
func (TestRunStatus) EnumDescriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{0}
}

type VMStatus int32

const (
	VMStatus_VM_STATUS_UNSPECIFIED  VMStatus = 0
	VMStatus_VM_STATUS_CREATING     VMStatus = 1
	VMStatus_VM_STATUS_BOOTING      VMStatus = 2
	VMStatus_VM_STATUS_READY        VMStatus = 3
	VMStatus_VM_STATUS_RUNNING_TEST VMStatus = 4
	VMStatus_VM_STATUS_STOPPING     VMStatus = 5
	VMStatus_VM_STATUS_STOPPED      VMStatus = 6
	VMStatus_VM_STATUS_ERROR        VMStatus = 7
	VMStatus_VM_STATUS_DESTROYED    VMStatus = 8
)

// Enum value maps for VMStatus.
var (
	VMStatus_name = map[int32]string{
		0: "VM_STATUS_UNSPECIFIED",
		1: "VM_STATUS_CREATING",
		2: "VM_STATUS_BOOTING",
		3: "VM_STATUS_READY",
		4: "VM_STATUS_RUNNING_TEST",
		5: "VM_STATUS_STOPPING",
		6: "VM_STATUS_STOPPED",
		7: "VM_STATUS_ERROR",
		8: "VM_STATUS_DESTROYED",
	}
	VMStatus_value = map[string]int32{
		"VM_STATUS_UNSPECIFIED":  0,
		"VM_STATUS_CREATING":     1,
		"VM_STATUS_BOOTING":      2,
		"VM_STATUS_READY":        3,
		"VM_STATUS_RUNNING_TEST": 4,
		"VM_STATUS_STOPPING":     5,
		"VM_STATUS_STOPPED":      6,
		"VM_STATUS_ERROR":        7,
		"VM_STATUS_DESTROYED":    8,
	}
)

func (x VMStatus) Enum() *VMStatus {
	p := new(VMStatus)
	*p = x
	return p
}

func (x VMStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VMStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_orchestrator_proto_enumTypes[1].Descriptor()
}

func (VMStatus) Type() protoreflect.EnumType {
	return &file_orchestrator_proto_enumTypes[1]
}

func (x VMStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VMStatus.Descriptor instead.
func (VMStatus) EnumDescriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{1}
}

type SubmitTestRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	TestSuiteId   string                 `protobuf:"bytes,2,opt,name=test_suite_id,json=testSuiteId,proto3" json:"test_suite_id,omitempty"`
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	RequestedBy   string                 `protobuf:"bytes,5,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTestRunRequest) Reset() {
	*x = SubmitTestRunRequest{}
	mi := &file_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTestRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTestRunRequest) ProtoMessage() {}

func (x *SubmitTestRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTestRunRequest.ProtoReflect.Descriptor instead.
func (*SubmitTestRunRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitTestRunRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SubmitTestRunRequest) GetTestSuiteId() string {
	if x != nil {
		return x.TestSuiteId
	}
	return ""
}

func (x *SubmitTestRunRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *SubmitTestRunRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SubmitTestRunRequest) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

type SubmitTestRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestRun       *TestRun               `protobuf:"bytes,1,opt,name=test_run,json=testRun,proto3" json:"test_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTestRunResponse) Reset() {
	*x = SubmitTestRunResponse{}
	mi := &file_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTestRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTestRunResponse) ProtoMessage() {}

func (x *SubmitTestRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTestRunResponse.ProtoReflect.Descriptor instead.
func (*SubmitTestRunResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitTestRunResponse) GetTestRun() *TestRun {
	if x != nil {
		return x.TestRun
	}
	return nil
}

type GetTestRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTestRunRequest) Reset() {
	*x = GetTestRunRequest{}
	mi := &file_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTestRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTestRunRequest) ProtoMessage() {}

func (x *GetTestRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTestRunRequest.ProtoReflect.Descriptor instead.
func (*GetTestRunRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *GetTestRunRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListTestRunsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Status        TestRunStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=dvf.orchestrator.v1.TestRunStatus" json:"status,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTestRunsRequest) Reset() {
	*x = ListTestRunsRequest{}
	mi := &file_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTestRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTestRunsRequest) ProtoMessage() {}

func (x *ListTestRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTestRunsRequest.ProtoReflect.Descriptor instead.
func (*ListTestRunsRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *ListTestRunsRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ListTestRunsRequest) GetStatus() TestRunStatus {
	if x != nil {
		return x.Status
	}
	return TestRunStatus_TEST_RUN_STATUS_UNSPECIFIED
}

func (x *ListTestRunsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTestRunsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListTestRunsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestRuns      []*TestRun             `protobuf:"bytes,1,rep,name=test_runs,json=testRuns,proto3" json:"test_runs,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTestRunsResponse) Reset() {
	*x = ListTestRunsResponse{}
	mi := &file_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTestRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTestRunsResponse) ProtoMessage() {}

func (x *ListTestRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTestRunsResponse.ProtoReflect.Descriptor instead.
func (*ListTestRunsResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *ListTestRunsResponse) GetTestRuns() []*TestRun {
	if x != nil {
		return x.TestRuns
	}
	return nil
}

func (x *ListTestRunsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type CancelTestRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTestRunRequest) Reset() {
	*x = CancelTestRunRequest{}
	mi := &file_orchestrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTestRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTestRunRequest) ProtoMessage() {}

func (x *CancelTestRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTestRunRequest.ProtoReflect.Descriptor instead.
func (*CancelTestRunRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{5}
}

func (x *CancelTestRunRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelTestRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTestRunResponse) Reset() {
	*x = CancelTestRunResponse{}
	mi := &file_orchestrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTestRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTestRunResponse) ProtoMessage() {}

func (x *CancelTestRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTestRunResponse.ProtoReflect.Descriptor instead.
func (*CancelTestRunResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{6}
}

func (x *CancelTestRunResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelTestRunResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TestRun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	TestSuiteId   string                 `protobuf:"bytes,3,opt,name=test_suite_id,json=testSuiteId,proto3" json:"test_suite_id,omitempty"`
	Status        TestRunStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=dvf.orchestrator.v1.TestRunStatus" json:"status,omitempty"`
	VmId          string                 `protobuf:"bytes,5,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Priority      int32                  `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	DurationMs    int64                  `protobuf:"varint,10,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	RequestedBy   string                 `protobuf:"bytes,11,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	Tags          []string               `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,13,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestRun) Reset() {
	*x = TestRun{}
	mi := &file_orchestrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRun) ProtoMessage() {}

func (x *TestRun) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRun.ProtoReflect.Descriptor instead.
func (*TestRun) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{7}
}

func (x *TestRun) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestRun) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *TestRun) GetTestSuiteId() string {
	if x != nil {
		return x.TestSuiteId
	}
	return ""
}

func (x *TestRun) GetStatus() TestRunStatus {
	if x != nil {
		return x.Status
	}
	return TestRunStatus_TEST_RUN_STATUS_UNSPECIFIED
}

func (x *TestRun) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *TestRun) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *TestRun) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TestRun) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *TestRun) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *TestRun) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *TestRun) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

func (x *TestRun) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *TestRun) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetTestResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestRunId     string                 `protobuf:"bytes,1,opt,name=test_run_id,json=testRunId,proto3" json:"test_run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTestResultsRequest) Reset() {
	*x = GetTestResultsRequest{}
	mi := &file_orchestrator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTestResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTestResultsRequest) ProtoMessage() {}

func (x *GetTestResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTestResultsRequest.ProtoReflect.Descriptor instead.
func (*GetTestResultsRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{8}
}

func (x *GetTestResultsRequest) GetTestRunId() string {
	if x != nil {
		return x.TestRunId
	}
	return ""
}

type GetTestResultsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*TestResult          `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTestResultsResponse) Reset() {
	*x = GetTestResultsResponse{}
	mi := &file_orchestrator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTestResultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTestResultsResponse) ProtoMessage() {}

func (x *GetTestResultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTestResultsResponse.ProtoReflect.Descriptor instead.
func (*GetTestResultsResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{9}
}

func (x *GetTestResultsResponse) GetResults() []*TestResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type TestResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TestRunId     string                 `protobuf:"bytes,2,opt,name=test_run_id,json=testRunId,proto3" json:"test_run_id,omitempty"`
	TestName      string                 `protobuf:"bytes,3,opt,name=test_name,json=testName,proto3" json:"test_name,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Status        TestRunStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=dvf.orchestrator.v1.TestRunStatus" json:"status,omitempty"`
	DurationMs    int64                  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Message       string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	Metrics       map[string]float64     `protobuf:"bytes,8,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Logs          string                 `protobuf:"bytes,9,opt,name=logs,proto3" json:"logs,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestResult) Reset() {
	*x = TestResult{}
	mi := &file_orchestrator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResult) ProtoMessage() {}

func (x *TestResult) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResult.ProtoReflect.Descriptor instead.
func (*TestResult) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{10}
}

func (x *TestResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestResult) GetTestRunId() string {
	if x != nil {
		return x.TestRunId
	}
	return ""
}

func (x *TestResult) GetTestName() string {
	if x != nil {
		return x.TestName
	}
	return ""
}

func (x *TestResult) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *TestResult) GetStatus() TestRunStatus {
	if x != nil {
		return x.Status
	}
	return TestRunStatus_TEST_RUN_STATUS_UNSPECIFIED
}

func (x *TestResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *TestResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TestResult) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *TestResult) GetLogs() string {
	if x != nil {
		return x.Logs
	}
	return ""
}

func (x *TestResult) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type ListVMsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        VMStatus               `protobuf:"varint,1,opt,name=status,proto3,enum=dvf.orchestrator.v1.VMStatus" json:"status,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVMsRequest) Reset() {
	*x = ListVMsRequest{}
	mi := &file_orchestrator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVMsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVMsRequest) ProtoMessage() {}

func (x *ListVMsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVMsRequest.ProtoReflect.Descriptor instead.
func (*ListVMsRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{11}
}

func (x *ListVMsRequest) GetStatus() VMStatus {
	if x != nil {
		return x.Status
	}
	return VMStatus_VM_STATUS_UNSPECIFIED
}

func (x *ListVMsRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type ListVMsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vms           []*VMInstance          `protobuf:"bytes,1,rep,name=vms,proto3" json:"vms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVMsResponse) Reset() {
	*x = ListVMsResponse{}
	mi := &file_orchestrator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVMsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVMsResponse) ProtoMessage() {}

func (x *ListVMsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVMsResponse.ProtoReflect.Descriptor instead.
func (*ListVMsResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{12}
}

func (x *ListVMsResponse) GetVms() []*VMInstance {
	if x != nil {
		return x.Vms
	}
	return nil
}

type GetVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVMRequest) Reset() {
	*x = GetVMRequest{}
	mi := &file_orchestrator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVMRequest) ProtoMessage() {}

func (x *GetVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVMRequest.ProtoReflect.Descriptor instead.
func (*GetVMRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{13}
}

func (x *GetVMRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type VMInstance struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status           VMStatus               `protobuf:"varint,2,opt,name=status,proto3,enum=dvf.orchestrator.v1.VMStatus" json:"status,omitempty"`
	DeviceId         string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	QmpSocketPath    string                 `protobuf:"bytes,4,opt,name=qmp_socket_path,json=qmpSocketPath,proto3" json:"qmp_socket_path,omitempty"`
	SerialPorts      []string               `protobuf:"bytes,5,rep,name=serial_ports,json=serialPorts,proto3" json:"serial_ports,omitempty"`
	Pid              int32                  `protobuf:"varint,6,opt,name=pid,proto3" json:"pid,omitempty"`
	AllocatedCpus    int32                  `protobuf:"varint,7,opt,name=allocated_cpus,json=allocatedCpus,proto3" json:"allocated_cpus,omitempty"`
	AllocatedMemMb   int32                  `protobuf:"varint,8,opt,name=allocated_mem_mb,json=allocatedMemMb,proto3" json:"allocated_mem_mb,omitempty"`
	ImagePath        string                 `protobuf:"bytes,9,opt,name=image_path,json=imagePath,proto3" json:"image_path,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	AgentStatus      string                 `protobuf:"bytes,11,opt,name=agent_status,json=agentStatus,proto3" json:"agent_status,omitempty"`
	LastHeartbeat    *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	CurrentTestRunId string                 `protobuf:"bytes,13,opt,name=current_test_run_id,json=currentTestRunId,proto3" json:"current_test_run_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VMInstance) Reset() {
	*x = VMInstance{}
	mi := &file_orchestrator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMInstance) ProtoMessage() {}

func (x *VMInstance) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMInstance.ProtoReflect.Descriptor instead.
func (*VMInstance) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{14}
}

func (x *VMInstance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VMInstance) GetStatus() VMStatus {
	if x != nil {
		return x.Status
	}
	return VMStatus_VM_STATUS_UNSPECIFIED
}

func (x *VMInstance) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *VMInstance) GetQmpSocketPath() string {
	if x != nil {
		return x.QmpSocketPath
	}
	return ""
}

func (x *VMInstance) GetSerialPorts() []string {
	if x != nil {
		return x.SerialPorts
	}
	return nil
}

func (x *VMInstance) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *VMInstance) GetAllocatedCpus() int32 {
	if x != nil {
		return x.AllocatedCpus
	}
	return 0
}

func (x *VMInstance) GetAllocatedMemMb() int32 {
	if x != nil {
		return x.AllocatedMemMb
	}
	return 0
}

func (x *VMInstance) GetImagePath() string {
	if x != nil {
		return x.ImagePath
	}
	return ""
}

func (x *VMInstance) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *VMInstance) GetAgentStatus() string {
	if x != nil {
		return x.AgentStatus
	}
	return ""
}

func (x *VMInstance) GetLastHeartbeat() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeat
	}
	return nil
}

func (x *VMInstance) GetCurrentTestRunId() string {
	if x != nil {
		return x.CurrentTestRunId
	}
	return ""
}

type ListDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_orchestrator_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{15}
}

type ListDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*DeviceEntry         `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_orchestrator_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{16}
}

func (x *ListDevicesResponse) GetDevices() []*DeviceEntry {
	if x != nil {
		return x.Devices
	}
	return nil
}

type GetDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceRequest) Reset() {
	*x = GetDeviceRequest{}
	mi := &file_orchestrator_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceRequest) ProtoMessage() {}

func (x *GetDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{17}
}

func (x *GetDeviceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeviceEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	VendorId       string                 `protobuf:"bytes,3,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	DeviceId       string                 `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	PciClass       string                 `protobuf:"bytes,5,opt,name=pci_class,json=pciClass,proto3" json:"pci_class,omitempty"`
	QemuDeviceName string                 `protobuf:"bytes,6,opt,name=qemu_device_name,json=qemuDeviceName,proto3" json:"qemu_device_name,omitempty"`
	DriverModule   string                 `protobuf:"bytes,7,opt,name=driver_module,json=driverModule,proto3" json:"driver_module,omitempty"`
	DriverPath     string                 `protobuf:"bytes,8,opt,name=driver_path,json=driverPath,proto3" json:"driver_path,omitempty"`
	Description    string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	Capabilities   []string               `protobuf:"bytes,10,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	TestSuites     []string               `protobuf:"bytes,11,rep,name=test_suites,json=testSuites,proto3" json:"test_suites,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeviceEntry) Reset() {
	*x = DeviceEntry{}
	mi := &file_orchestrator_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceEntry) ProtoMessage() {}

func (x *DeviceEntry) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceEntry.ProtoReflect.Descriptor instead.
func (*DeviceEntry) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{18}
}

func (x *DeviceEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeviceEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeviceEntry) GetVendorId() string {
	if x != nil {
		return x.VendorId
	}
	return ""
}

func (x *DeviceEntry) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceEntry) GetPciClass() string {
	if x != nil {
		return x.PciClass
	}
	return ""
}

func (x *DeviceEntry) GetQemuDeviceName() string {
	if x != nil {
		return x.QemuDeviceName
	}
	return ""
}

func (x *DeviceEntry) GetDriverModule() string {
	if x != nil {
		return x.DriverModule
	}
	return ""
}

func (x *DeviceEntry) GetDriverPath() string {
	if x != nil {
		return x.DriverPath
	}
	return ""
}

func (x *DeviceEntry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DeviceEntry) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *DeviceEntry) GetTestSuites() []string {
	if x != nil {
		return x.TestSuites
	}
	return nil
}

type GetHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthRequest) Reset() {
	*x = GetHealthRequest{}
	mi := &file_orchestrator_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthRequest) ProtoMessage() {}

func (x *GetHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthRequest.ProtoReflect.Descriptor instead.
func (*GetHealthRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{19}
}

type GetHealthResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Status        string                      `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "healthy", "degraded", "unhealthy"
	Components    map[string]*ComponentHealth `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     *timestamppb.Timestamp      `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthResponse) Reset() {
	*x = GetHealthResponse{}
	mi := &file_orchestrator_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthResponse) ProtoMessage() {}

func (x *GetHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthResponse.ProtoReflect.Descriptor instead.
func (*GetHealthResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{20}
}

func (x *GetHealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetHealthResponse) GetComponents() map[string]*ComponentHealth {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *GetHealthResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ComponentHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentHealth) Reset() {
	*x = ComponentHealth{}
	mi := &file_orchestrator_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentHealth) ProtoMessage() {}

func (x *ComponentHealth) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentHealth.ProtoReflect.Descriptor instead.
func (*ComponentHealth) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{21}
}

func (x *ComponentHealth) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ComponentHealth) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_orchestrator_proto protoreflect.FileDescriptor

const file_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x12orchestrator.proto\x12\x13dvf.orchestrator.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaa\x01\n" +
	"\x14SubmitTestRunRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\"\n" +
	"\rtest_suite_id\x18\x02 \x01(\tR\vtestSuiteId\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12!\n" +
	"\frequested_by\x18\x05 \x01(\tR\vrequestedBy\"P\n" +
	"\x15SubmitTestRunResponse\x127\n" +
	"\btest_run\x18\x01 \x01(\v2\x1c.dvf.orchestrator.v1.TestRunR\atestRun\"#\n" +
	"\x11GetTestRunRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x9c\x01\n" +
	"\x13ListTestRunsRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12:\n" +
	"\x06status\x18\x02 \x01(\x0e2\".dvf.orchestrator.v1.TestRunStatusR\x06status\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"r\n" +
	"\x14ListTestRunsResponse\x129\n" +
	"\ttest_runs\x18\x01 \x03(\v2\x1c.dvf.orchestrator.v1.TestRunR\btestRuns\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"&\n" +
	"\x14CancelTestRunRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"K\n" +
	"\x15CancelTestRunResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xf9\x03\n" +
	"\aTestRun\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\"\n" +
	"\rtest_suite_id\x18\x03 \x01(\tR\vtestSuiteId\x12:\n" +
	"\x06status\x18\x04 \x01(\x0e2\".dvf.orchestrator.v1.TestRunStatusR\x06status\x12\x13\n" +
	"\x05vm_id\x18\x05 \x01(\tR\x04vmId\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"started_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12\x1f\n" +
	"\vduration_ms\x18\n" +
	" \x01(\x03R\n" +
	"durationMs\x12!\n" +
	"\frequested_by\x18\v \x01(\tR\vrequestedBy\x12\x12\n" +
	"\x04tags\x18\f \x03(\tR\x04tags\x12#\n" +
	"\rerror_message\x18\r \x01(\tR\ferrorMessage\"7\n" +
	"\x15GetTestResultsRequest\x12\x1e\n" +
	"\vtest_run_id\x18\x01 \x01(\tR\ttestRunId\"S\n" +
	"\x16GetTestResultsResponse\x129\n" +
	"\aresults\x18\x01 \x03(\v2\x1f.dvf.orchestrator.v1.TestResultR\aresults\"\xc3\x03\n" +
	"\n" +
	"TestResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\vtest_run_id\x18\x02 \x01(\tR\ttestRunId\x12\x1b\n" +
	"\ttest_name\x18\x03 \x01(\tR\btestName\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12:\n" +
	"\x06status\x18\x05 \x01(\x0e2\".dvf.orchestrator.v1.TestRunStatusR\x06status\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x03R\n" +
	"durationMs\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x12F\n" +
	"\ametrics\x18\b \x03(\v2,.dvf.orchestrator.v1.TestResult.MetricsEntryR\ametrics\x12\x12\n" +
	"\x04logs\x18\t \x01(\tR\x04logs\x12=\n" +
	"\fcompleted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"d\n" +
	"\x0eListVMsRequest\x125\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1d.dvf.orchestrator.v1.VMStatusR\x06status\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\"D\n" +
	"\x0fListVMsResponse\x121\n" +
	"\x03vms\x18\x01 \x03(\v2\x1f.dvf.orchestrator.v1.VMInstanceR\x03vms\"\x1e\n" +
	"\fGetVMRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x8d\x04\n" +
	"\n" +
	"VMInstance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.dvf.orchestrator.v1.VMStatusR\x06status\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12&\n" +
	"\x0fqmp_socket_path\x18\x04 \x01(\tR\rqmpSocketPath\x12!\n" +
	"\fserial_ports\x18\x05 \x03(\tR\vserialPorts\x12\x10\n" +
	"\x03pid\x18\x06 \x01(\x05R\x03pid\x12%\n" +
	"\x0eallocated_cpus\x18\a \x01(\x05R\rallocatedCpus\x12(\n" +
	"\x10allocated_mem_mb\x18\b \x01(\x05R\x0eallocatedMemMb\x12\x1d\n" +
	"\n" +
	"image_path\x18\t \x01(\tR\timagePath\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12!\n" +
	"\fagent_status\x18\v \x01(\tR\vagentStatus\x12A\n" +
	"\x0elast_heartbeat\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\rlastHeartbeat\x12-\n" +
	"\x13current_test_run_id\x18\r \x01(\tR\x10currentTestRunId\"\x14\n" +
	"\x12ListDevicesRequest\"Q\n" +
	"\x13ListDevicesResponse\x12:\n" +
	"\adevices\x18\x01 \x03(\v2 .dvf.orchestrator.v1.DeviceEntryR\adevices\"\"\n" +
	"\x10GetDeviceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xdf\x02\n" +
	"\vDeviceEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tvendor_id\x18\x03 \x01(\tR\bvendorId\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\tR\bdeviceId\x12\x1b\n" +
	"\tpci_class\x18\x05 \x01(\tR\bpciClass\x12(\n" +
	"\x10qemu_device_name\x18\x06 \x01(\tR\x0eqemuDeviceName\x12#\n" +
	"\rdriver_module\x18\a \x01(\tR\fdriverModule\x12\x1f\n" +
	"\vdriver_path\x18\b \x01(\tR\n" +
	"driverPath\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12\"\n" +
	"\fcapabilities\x18\n" +
	" \x03(\tR\fcapabilities\x12\x1f\n" +
	"\vtest_suites\x18\v \x03(\tR\n" +
	"testSuites\"\x12\n" +
	"\x10GetHealthRequest\"\xa2\x02\n" +
	"\x11GetHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12V\n" +
	"\n" +
	"components\x18\x02 \x03(\v26.dvf.orchestrator.v1.GetHealthResponse.ComponentsEntryR\n" +
	"components\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1ac\n" +
	"\x0fComponentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\x05value\x18\x02 \x01(\v2$.dvf.orchestrator.v1.ComponentHealthR\x05value:\x028\x01\"C\n" +
	"\x0fComponentHealth\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\x97\x02\n" +
	"\rTestRunStatus\x12\x1f\n" +
	"\x1bTEST_RUN_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17TEST_RUN_STATUS_PENDING\x10\x01\x12\x1a\n" +
	"\x16TEST_RUN_STATUS_QUEUED\x10\x02\x12\x1b\n" +
	"\x17TEST_RUN_STATUS_RUNNING\x10\x03\x12\x1a\n" +
	"\x16TEST_RUN_STATUS_PASSED\x10\x04\x12\x1a\n" +
	"\x16TEST_RUN_STATUS_FAILED\x10\x05\x12\x1b\n" +
	"\x17TEST_RUN_STATUS_ERRORED\x10\x06\x12\x1d\n" +
	"\x19TEST_RUN_STATUS_CANCELLED\x10\a\x12\x1b\n" +
	"\x17TEST_RUN_STATUS_TIMEOUT\x10\b*\xe2\x01\n" +
	"\bVMStatus\x12\x19\n" +
	"\x15VM_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12VM_STATUS_CREATING\x10\x01\x12\x15\n" +
	"\x11VM_STATUS_BOOTING\x10\x02\x12\x13\n" +
	"\x0fVM_STATUS_READY\x10\x03\x12\x1a\n" +
	"\x16VM_STATUS_RUNNING_TEST\x10\x04\x12\x16\n" +
	"\x12VM_STATUS_STOPPING\x10\x05\x12\x15\n" +
	"\x11VM_STATUS_STOPPED\x10\x06\x12\x13\n" +
	"\x0fVM_STATUS_ERROR\x10\a\x12\x17\n" +
	"\x13VM_STATUS_DESTROYED\x10\b2\xf5\t\n" +
	"\x13OrchestratorService\x12\x84\x01\n" +
	"\rSubmitTestRun\x12).dvf.orchestrator.v1.SubmitTestRunRequest\x1a*.dvf.orchestrator.v1.SubmitTestRunResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/v1/test-runs\x12r\n" +
	"\n" +
	"GetTestRun\x12&.dvf.orchestrator.v1.GetTestRunRequest\x1a\x1c.dvf.orchestrator.v1.TestRun\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/test-runs/{id}\x12~\n" +
	"\fListTestRuns\x12(.dvf.orchestrator.v1.ListTestRunsRequest\x1a).dvf.orchestrator.v1.ListTestRunsResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/test-runs\x12\x90\x01\n" +
	"\rCancelTestRun\x12).dvf.orchestrator.v1.CancelTestRunRequest\x1a*.dvf.orchestrator.v1.CancelTestRunResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/test-runs/{id}/cancel\x12\x9a\x01\n" +
	"\x0eGetTestResults\x12*.dvf.orchestrator.v1.GetTestResultsRequest\x1a+.dvf.orchestrator.v1.GetTestResultsResponse\"/\x82\xd3\xe4\x93\x02)\x12'/api/v1/test-runs/{test_run_id}/results\x12i\n" +
	"\aListVMs\x12#.dvf.orchestrator.v1.ListVMsRequest\x1a$.dvf.orchestrator.v1.ListVMsResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/api/v1/vms\x12e\n" +
	"\x05GetVM\x12!.dvf.orchestrator.v1.GetVMRequest\x1a\x1f.dvf.orchestrator.v1.VMInstance\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/vms/{id}\x12y\n" +
	"\vListDevices\x12'.dvf.orchestrator.v1.ListDevicesRequest\x1a(.dvf.orchestrator.v1.ListDevicesResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/devices\x12r\n" +
	"\tGetDevice\x12%.dvf.orchestrator.v1.GetDeviceRequest\x1a .dvf.orchestrator.v1.DeviceEntry\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/devices/{id}\x12r\n" +
	"\tGetHealth\x12%.dvf.orchestrator.v1.GetHealthRequest\x1a&.dvf.orchestrator.v1.GetHealthResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/healthBXZVgithub.com/kartheekbudime/driver-validation-suite/go-orchestrator/proto/orchestratorpbb\x06proto3"

var (
	file_orchestrator_proto_rawDescOnce sync.Once
	file_orchestrator_proto_rawDescData []byte
)

func file_orchestrator_proto_rawDescGZIP() []byte {
	file_orchestrator_proto_rawDescOnce.Do(func() {
		file_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orchestrator_proto_rawDesc), len(file_orchestrator_proto_rawDesc)))
	})
	return file_orchestrator_proto_rawDescData
}

var file_orchestrator_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_orchestrator_proto_goTypes = []any{
	(TestRunStatus)(0),             // 0: dvf.orchestrator.v1.TestRunStatus
	(VMStatus)(0),                  // 1: dvf.orchestrator.v1.VMStatus
	(*SubmitTestRunRequest)(nil),   // 2: dvf.orchestrator.v1.SubmitTestRunRequest
	(*SubmitTestRunResponse)(nil),  // 3: dvf.orchestrator.v1.SubmitTestRunResponse
	(*GetTestRunRequest)(nil),      // 4: dvf.orchestrator.v1.GetTestRunRequest
	(*ListTestRunsRequest)(nil),    // 5: dvf.orchestrator.v1.ListTestRunsRequest
	(*ListTestRunsResponse)(nil),   // 6: dvf.orchestrator.v1.ListTestRunsResponse
	(*CancelTestRunRequest)(nil),   // 7: dvf.orchestrator.v1.CancelTestRunRequest
	(*CancelTestRunResponse)(nil),  // 8: dvf.orchestrator.v1.CancelTestRunResponse
	(*TestRun)(nil),                // 9: dvf.orchestrator.v1.TestRun
	(*GetTestResultsRequest)(nil),  // 10: dvf.orchestrator.v1.GetTestResultsRequest
	(*GetTestResultsResponse)(nil), // 11: dvf.orchestrator.v1.GetTestResultsResponse
	(*TestResult)(nil),             // 12: dvf.orchestrator.v1.TestResult
	(*ListVMsRequest)(nil),         // 13: dvf.orchestrator.v1.ListVMsRequest
	(*ListVMsResponse)(nil),        // 14: dvf.orchestrator.v1.ListVMsResponse
	(*GetVMRequest)(nil),           // 15: dvf.orchestrator.v1.GetVMRequest
	(*VMInstance)(nil),             // 16: dvf.orchestrator.v1.VMInstance
	(*ListDevicesRequest)(nil),     // 17: dvf.orchestrator.v1.ListDevicesRequest
	(*ListDevicesResponse)(nil),    // 18: dvf.orchestrator.v1.ListDevicesResponse
	(*GetDeviceRequest)(nil),       // 19: dvf.orchestrator.v1.GetDeviceRequest
	(*DeviceEntry)(nil),            // 20: dvf.orchestrator.v1.DeviceEntry
	(*GetHealthRequest)(nil),       // 21: dvf.orchestrator.v1.GetHealthRequest
	(*GetHealthResponse)(nil),      // 22: dvf.orchestrator.v1.GetHealthResponse
	(*ComponentHealth)(nil),        // 23: dvf.orchestrator.v1.ComponentHealth
	nil,                            // 24: dvf.orchestrator.v1.TestResult.MetricsEntry
	nil,                            // 25: dvf.orchestrator.v1.GetHealthResponse.ComponentsEntry
	(*timestamppb.Timestamp)(nil),  // 26: google.protobuf.Timestamp
}
var file_orchestrator_proto_depIdxs = []int32{
	9,  // 0: dvf.orchestrator.v1.SubmitTestRunResponse.test_run:type_name -> dvf.orchestrator.v1.TestRun
	0,  // 1: dvf.orchestrator.v1.ListTestRunsRequest.status:type_name -> dvf.orchestrator.v1.TestRunStatus
	9,  // 2: dvf.orchestrator.v1.ListTestRunsResponse.test_runs:type_name -> dvf.orchestrator.v1.TestRun
	0,  // 3: dvf.orchestrator.v1.TestRun.status:type_name -> dvf.orchestrator.v1.TestRunStatus
	26, // 4: dvf.orchestrator.v1.TestRun.created_at:type_name -> google.protobuf.Timestamp
	26, // 5: dvf.orchestrator.v1.TestRun.started_at:type_name -> google.protobuf.Timestamp
	26, // 6: dvf.orchestrator.v1.TestRun.completed_at:type_name -> google.protobuf.Timestamp
	12, // 7: dvf.orchestrator.v1.GetTestResultsResponse.results:type_name -> dvf.orchestrator.v1.TestResult
	0,  // 8: dvf.orchestrator.v1.TestResult.status:type_name -> dvf.orchestrator.v1.TestRunStatus
	24, // 9: dvf.orchestrator.v1.TestResult.metrics:type_name -> dvf.orchestrator.v1.TestResult.MetricsEntry
	26, // 10: dvf.orchestrator.v1.TestResult.completed_at:type_name -> google.protobuf.Timestamp
	1,  // 11: dvf.orchestrator.v1.ListVMsRequest.status:type_name -> dvf.orchestrator.v1.VMStatus
	16, // 12: dvf.orchestrator.v1.ListVMsResponse.vms:type_name -> dvf.orchestrator.v1.VMInstance
	1,  // 13: dvf.orchestrator.v1.VMInstance.status:type_name -> dvf.orchestrator.v1.VMStatus
	26, // 14: dvf.orchestrator.v1.VMInstance.created_at:type_name -> google.protobuf.Timestamp
	26, // 15: dvf.orchestrator.v1.VMInstance.last_heartbeat:type_name -> google.protobuf.Timestamp
	20, // 16: dvf.orchestrator.v1.ListDevicesResponse.devices:type_name -> dvf.orchestrator.v1.DeviceEntry
	25, // 17: dvf.orchestrator.v1.GetHealthResponse.components:type_name -> dvf.orchestrator.v1.GetHealthResponse.ComponentsEntry
	26, // 18: dvf.orchestrator.v1.GetHealthResponse.timestamp:type_name -> google.protobuf.Timestamp
	23, // 19: dvf.orchestrator.v1.GetHealthResponse.ComponentsEntry.value:type_name -> dvf.orchestrator.v1.ComponentHealth
	2,  // 20: dvf.orchestrator.v1.OrchestratorService.SubmitTestRun:input_type -> dvf.orchestrator.v1.SubmitTestRunRequest
	4,  // 21: dvf.orchestrator.v1.OrchestratorService.GetTestRun:input_type -> dvf.orchestrator.v1.GetTestRunRequest
	5,  // 22: dvf.orchestrator.v1.OrchestratorService.ListTestRuns:input_type -> dvf.orchestrator.v1.ListTestRunsRequest
	7,  // 23: dvf.orchestrator.v1.OrchestratorService.CancelTestRun:input_type -> dvf.orchestrator.v1.CancelTestRunRequest
	10, // 24: dvf.orchestrator.v1.OrchestratorService.GetTestResults:input_type -> dvf.orchestrator.v1.GetTestResultsRequest
	13, // 25: dvf.orchestrator.v1.OrchestratorService.ListVMs:input_type -> dvf.orchestrator.v1.ListVMsRequest
	15, // 26: dvf.orchestrator.v1.OrchestratorService.GetVM:input_type -> dvf.orchestrator.v1.GetVMRequest
	17, // 27: dvf.orchestrator.v1.OrchestratorService.ListDevices:input_type -> dvf.orchestrator.v1.ListDevicesRequest
	19, // 28: dvf.orchestrator.v1.OrchestratorService.GetDevice:input_type -> dvf.orchestrator.v1.GetDeviceRequest
	21, // 29: dvf.orchestrator.v1.OrchestratorService.GetHealth:input_type -> dvf.orchestrator.v1.GetHealthRequest
	3,  // 30: dvf.orchestrator.v1.OrchestratorService.SubmitTestRun:output_type -> dvf.orchestrator.v1.SubmitTestRunResponse
	9,  // 31: dvf.orchestrator.v1.OrchestratorService.GetTestRun:output_type -> dvf.orchestrator.v1.TestRun
	6,  // 32: dvf.orchestrator.v1.OrchestratorService.ListTestRuns:output_type -> dvf.orchestrator.v1.ListTestRunsResponse
	8,  // 33: dvf.orchestrator.v1.OrchestratorService.CancelTestRun:output_type -> dvf.orchestrator.v1.CancelTestRunResponse
	11, // 34: dvf.orchestrator.v1.OrchestratorService.GetTestResults:output_type -> dvf.orchestrator.v1.GetTestResultsResponse
	14, // 35: dvf.orchestrator.v1.OrchestratorService.ListVMs:output_type -> dvf.orchestrator.v1.ListVMsResponse
	16, // 36: dvf.orchestrator.v1.OrchestratorService.GetVM:output_type -> dvf.orchestrator.v1.VMInstance
	18, // 37: dvf.orchestrator.v1.OrchestratorService.ListDevices:output_type -> dvf.orchestrator.v1.ListDevicesResponse
	20, // 38: dvf.orchestrator.v1.OrchestratorService.GetDevice:output_type -> dvf.orchestrator.v1.DeviceEntry
	22, // 39: dvf.orchestrator.v1.OrchestratorService.GetHealth:output_type -> dvf.orchestrator.v1.GetHealthResponse
	30, // [30:40] is the sub-list for method output_type
	20, // [20:30] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_orchestrator_proto_init() }
func file_orchestrator_proto_init() {
	if File_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orchestrator_proto_rawDesc), len(file_orchestrator_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orchestrator_proto_goTypes,
		DependencyIndexes: file_orchestrator_proto_depIdxs,
		EnumInfos:         file_orchestrator_proto_enumTypes,
		MessageInfos:      file_orchestrator_proto_msgTypes,
	}.Build()
	File_orchestrator_proto = out.File
	file_orchestrator_proto_goTypes = nil
	file_orchestrator_proto_depIdxs = nil
}
