// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.6
// source: orchestrator.proto

package orchestratorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrchestratorService_SubmitTestRun_FullMethodName  = "/dvf.orchestrator.v1.OrchestratorService/SubmitTestRun"
	OrchestratorService_GetTestRun_FullMethodName     = "/dvf.orchestrator.v1.OrchestratorService/GetTestRun"
	OrchestratorService_ListTestRuns_FullMethodName   = "/dvf.orchestrator.v1.OrchestratorService/ListTestRuns"
	OrchestratorService_CancelTestRun_FullMethodName  = "/dvf.orchestrator.v1.OrchestratorService/CancelTestRun"
	OrchestratorService_GetTestResults_FullMethodName = "/dvf.orchestrator.v1.OrchestratorService/GetTestResults"
	OrchestratorService_ListVMs_FullMethodName        = "/dvf.orchestrator.v1.OrchestratorService/ListVMs"
	OrchestratorService_GetVM_FullMethodName          = "/dvf.orchestrator.v1.OrchestratorService/GetVM"
	OrchestratorService_ListDevices_FullMethodName    = "/dvf.orchestrator.v1.OrchestratorService/ListDevices"
	OrchestratorService_GetDevice_FullMethodName      = "/dvf.orchestrator.v1.OrchestratorService/GetDevice"
	OrchestratorService_GetHealth_FullMethodName      = "/dvf.orchestrator.v1.OrchestratorService/GetHealth"
)

// OrchestratorServiceClient is the client API for OrchestratorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OrchestratorService is the primary API for the Device Validation Framework.
// It handles test run submission, VM management, device queries, and result retrieval.
type OrchestratorServiceClient interface {
	// SubmitTestRun queues a new test run for a given device and test suite.
	SubmitTestRun(ctx context.Context, in *SubmitTestRunRequest, opts ...grpc.CallOption) (*SubmitTestRunResponse, error)
	// GetTestRun retrieves details of a specific test run by ID.
	GetTestRun(ctx context.Context, in *GetTestRunRequest, opts ...grpc.CallOption) (*TestRun, error)
	// ListTestRuns returns test runs with optional filtering.
	ListTestRuns(ctx context.Context, in *ListTestRunsRequest, opts ...grpc.CallOption) (*ListTestRunsResponse, error)
	// CancelTestRun cancels a pending or running test run.
	CancelTestRun(ctx context.Context, in *CancelTestRunRequest, opts ...grpc.CallOption) (*CancelTestRunResponse, error)
	// GetTestResults retrieves the detailed results of a completed test run.
	GetTestResults(ctx context.Context, in *GetTestResultsRequest, opts ...grpc.CallOption) (*GetTestResultsResponse, error)
	// ListVMs returns all virtual machines with optional filtering.
	ListVMs(ctx context.Context, in *ListVMsRequest, opts ...grpc.CallOption) (*ListVMsResponse, error)
	// GetVM retrieves details of a specific VM.
	GetVM(ctx context.Context, in *GetVMRequest, opts ...grpc.CallOption) (*VMInstance, error)
	// ListDevices returns all registered devices from the device registry.
	ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error)
	// GetDevice retrieves a specific device from the registry.
	GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*DeviceEntry, error)
	// GetHealth returns the health status of the orchestrator and its dependencies.
	GetHealth(ctx context.Context, in *GetHealthRequest, opts ...grpc.CallOption) (*GetHealthResponse, error)
}

type orchestratorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorServiceClient(cc grpc.ClientConnInterface) OrchestratorServiceClient {
	return &orchestratorServiceClient{cc}
}

func (c *orchestratorServiceClient) SubmitTestRun(ctx context.Context, in *SubmitTestRunRequest, opts ...grpc.CallOption) (*SubmitTestRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitTestRunResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_SubmitTestRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) GetTestRun(ctx context.Context, in *GetTestRunRequest, opts ...grpc.CallOption) (*TestRun, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestRun)
	err := c.cc.Invoke(ctx, OrchestratorService_GetTestRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) ListTestRuns(ctx context.Context, in *ListTestRunsRequest, opts ...grpc.CallOption) (*ListTestRunsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTestRunsResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_ListTestRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) CancelTestRun(ctx context.Context, in *CancelTestRunRequest, opts ...grpc.CallOption) (*CancelTestRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelTestRunResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_CancelTestRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) GetTestResults(ctx context.Context, in *GetTestResultsRequest, opts ...grpc.CallOption) (*GetTestResultsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTestResultsResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_GetTestResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) ListVMs(ctx context.Context, in *ListVMsRequest, opts ...grpc.CallOption) (*ListVMsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVMsResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_ListVMs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) GetVM(ctx context.Context, in *GetVMRequest, opts ...grpc.CallOption) (*VMInstance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMInstance)
	err := c.cc.Invoke(ctx, OrchestratorService_GetVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDevicesResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_ListDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*DeviceEntry, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceEntry)
	err := c.cc.Invoke(ctx, OrchestratorService_GetDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) GetHealth(ctx context.Context, in *GetHealthRequest, opts ...grpc.CallOption) (*GetHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHealthResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_GetHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchestratorServiceServer is the server API for OrchestratorService service.
// All implementations must embed UnimplementedOrchestratorServiceServer
// for forward compatibility.
//
// OrchestratorService is the primary API for the Device Validation Framework.
// It handles test run submission, VM management, device queries, and result retrieval.
type OrchestratorServiceServer interface {
	// SubmitTestRun queues a new test run for a given device and test suite.
	SubmitTestRun(context.Context, *SubmitTestRunRequest) (*SubmitTestRunResponse, error)
	// GetTestRun retrieves details of a specific test run by ID.
	GetTestRun(context.Context, *GetTestRunRequest) (*TestRun, error)
	// ListTestRuns returns test runs with optional filtering.
	ListTestRuns(context.Context, *ListTestRunsRequest) (*ListTestRunsResponse, error)
	// CancelTestRun cancels a pending or running test run.
	CancelTestRun(context.Context, *CancelTestRunRequest) (*CancelTestRunResponse, error)
	// GetTestResults retrieves the detailed results of a completed test run.
	GetTestResults(context.Context, *GetTestResultsRequest) (*GetTestResultsResponse, error)
	// ListVMs returns all virtual machines with optional filtering.
	ListVMs(context.Context, *ListVMsRequest) (*ListVMsResponse, error)
	// GetVM retrieves details of a specific VM.
	GetVM(context.Context, *GetVMRequest) (*VMInstance, error)
	// ListDevices returns all registered devices from the device registry.
	ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	// GetDevice retrieves a specific device from the registry.
	GetDevice(context.Context, *GetDeviceRequest) (*DeviceEntry, error)
	// GetHealth returns the health status of the orchestrator and its dependencies.
	GetHealth(context.Context, *GetHealthRequest) (*GetHealthResponse, error)
	mustEmbedUnimplementedOrchestratorServiceServer()
}

// UnimplementedOrchestratorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrchestratorServiceServer struct{}

func (UnimplementedOrchestratorServiceServer) SubmitTestRun(context.Context, *SubmitTestRunRequest) (*SubmitTestRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitTestRun not implemented")
}
func (UnimplementedOrchestratorServiceServer) GetTestRun(context.Context, *GetTestRunRequest) (*TestRun, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTestRun not implemented")
}
func (UnimplementedOrchestratorServiceServer) ListTestRuns(context.Context, *ListTestRunsRequest) (*ListTestRunsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTestRuns not implemented")
}
func (UnimplementedOrchestratorServiceServer) CancelTestRun(context.Context, *CancelTestRunRequest) (*CancelTestRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTestRun not implemented")
}
func (UnimplementedOrchestratorServiceServer) GetTestResults(context.Context, *GetTestResultsRequest) (*GetTestResultsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTestResults not implemented")
}
func (UnimplementedOrchestratorServiceServer) ListVMs(context.Context, *ListVMsRequest) (*ListVMsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVMs not implemented")
}
func (UnimplementedOrchestratorServiceServer) GetVM(context.Context, *GetVMRequest) (*VMInstance, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVM not implemented")
}
func (UnimplementedOrchestratorServiceServer) ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDevices not implemented")
}
func (UnimplementedOrchestratorServiceServer) GetDevice(context.Context, *GetDeviceRequest) (*DeviceEntry, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDevice not implemented")
}
func (UnimplementedOrchestratorServiceServer) GetHealth(context.Context, *GetHealthRequest) (*GetHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHealth not implemented")
}
func (UnimplementedOrchestratorServiceServer) mustEmbedUnimplementedOrchestratorServiceServer() {}
func (UnimplementedOrchestratorServiceServer) testEmbeddedByValue()                             {}

// UnsafeOrchestratorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestratorServiceServer will
// result in compilation errors.
type UnsafeOrchestratorServiceServer interface {
	mustEmbedUnimplementedOrchestratorServiceServer()
}

func RegisterOrchestratorServiceServer(s grpc.ServiceRegistrar, srv OrchestratorServiceServer) {
	// If the following call panics, it indicates UnimplementedOrchestratorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrchestratorService_ServiceDesc, srv)
}

func _OrchestratorService_SubmitTestRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitTestRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).SubmitTestRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_SubmitTestRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).SubmitTestRun(ctx, req.(*SubmitTestRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_GetTestRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTestRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).GetTestRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_GetTestRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).GetTestRun(ctx, req.(*GetTestRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_ListTestRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTestRunsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).ListTestRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_ListTestRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).ListTestRuns(ctx, req.(*ListTestRunsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_CancelTestRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTestRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).CancelTestRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_CancelTestRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).CancelTestRun(ctx, req.(*CancelTestRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_GetTestResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTestResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).GetTestResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_GetTestResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).GetTestResults(ctx, req.(*GetTestResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_ListVMs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVMsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).ListVMs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_ListVMs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).ListVMs(ctx, req.(*ListVMsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_GetVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).GetVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_GetVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).GetVM(ctx, req.(*GetVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_ListDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).ListDevices(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_GetDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).GetDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_GetDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).GetDevice(ctx, req.(*GetDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_GetHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).GetHealth(ctx, req.(*GetHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrchestratorService_ServiceDesc is the grpc.ServiceDesc for OrchestratorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrchestratorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dvf.orchestrator.v1.OrchestratorService",
	HandlerType: (*OrchestratorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitTestRun",
			Handler:    _OrchestratorService_SubmitTestRun_Handler,
		},
		{
			MethodName: "GetTestRun",
			Handler:    _OrchestratorService_GetTestRun_Handler,
		},
		{
			MethodName: "ListTestRuns",
			Handler:    _OrchestratorService_ListTestRuns_Handler,
		},
		{
			MethodName: "CancelTestRun",
			Handler:    _OrchestratorService_CancelTestRun_Handler,
		},
		{
			MethodName: "GetTestResults",
			Handler:    _OrchestratorService_GetTestResults_Handler,
		},
		{
			MethodName: "ListVMs",
			Handler:    _OrchestratorService_ListVMs_Handler,
		},
		{
			MethodName: "GetVM",
			Handler:    _OrchestratorService_GetVM_Handler,
		},
		{
			MethodName: "ListDevices",
			Handler:    _OrchestratorService_ListDevices_Handler,
		},
		{
			MethodName: "GetDevice",
			Handler:    _OrchestratorService_GetDevice_Handler,
		},
		{
			MethodName: "GetHealth",
			Handler:    _OrchestratorService_GetHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orchestrator.proto",
}
