# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import agent_pb2 as agent__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub:
    """AgentService handles guest agent registration and command dispatch.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterAgent = channel.unary_unary(
                '/dvf.agent.v1.AgentService/RegisterAgent',
                request_serializer=agent__pb2.RegisterAgentRequest.SerializeToString,
                response_deserializer=agent__pb2.RegisterAgentResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/dvf.agent.v1.AgentService/Heartbeat',
                request_serializer=agent__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=agent__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.GetCommand = channel.unary_unary(
                '/dvf.agent.v1.AgentService/GetCommand',
                request_serializer=agent__pb2.GetCommandRequest.SerializeToString,
                response_deserializer=agent__pb2.Command.FromString,
                _registered_method=True)
        self.ReportResult = channel.unary_unary(
                '/dvf.agent.v1.AgentService/ReportResult',
                request_serializer=agent__pb2.ReportResultRequest.SerializeToString,
                response_deserializer=agent__pb2.ReportResultResponse.FromString,
                _registered_method=True)


class AgentServiceServicer:
    """AgentService handles guest agent registration and command dispatch.
    """

    def RegisterAgent(self, request, context):
        """RegisterAgent is called by a guest agent on startup to announce itself.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Heartbeat is sent periodically by the agent to report its health.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCommand(self, request, context):
        """GetCommand is polled by the agent to receive the next command from the orchestrator.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportResult(self, request, context):
        """ReportResult is called by the agent to report the result of a completed command.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=agent__pb2.RegisterAgentRequest.FromString,
                    response_serializer=agent__pb2.RegisterAgentResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=agent__pb2.HeartbeatRequest.FromString,
                    response_serializer=agent__pb2.HeartbeatResponse.SerializeToString,
            ),
            'GetCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCommand,
                    request_deserializer=agent__pb2.GetCommandRequest.FromString,
                    response_serializer=agent__pb2.Command.SerializeToString,
            ),
            'ReportResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportResult,
                    request_deserializer=agent__pb2.ReportResultRequest.FromString,
                    response_serializer=agent__pb2.ReportResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dvf.agent.v1.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dvf.agent.v1.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService:
    """AgentService handles guest agent registration and command dispatch.
    """

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dvf.agent.v1.AgentService/RegisterAgent',
            agent__pb2.RegisterAgentRequest.SerializeToString,
            agent__pb2.RegisterAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dvf.agent.v1.AgentService/Heartbeat',
            agent__pb2.HeartbeatRequest.SerializeToString,
            agent__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dvf.agent.v1.AgentService/GetCommand',
            agent__pb2.GetCommandRequest.SerializeToString,
            agent__pb2.Command.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dvf.agent.v1.AgentService/ReportResult',
            agent__pb2.ReportResultRequest.SerializeToString,
            agent__pb2.ReportResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
