# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\x10\x64vf.telemetry.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf4\x01\n\x08LogEntry\x12\r\n\x05vm_id\x18\x01 \x01(\t\x12\x10\n\x08\x61gent_id\x18\x02 \x01(\t\x12\x10\n\x08severity\x18\x03 \x01(\t\x12\x0e\n\x06source\x18\x04 \x01(\t\x12\x0f\n\x07message\x18\x05 \x01(\t\x12\x36\n\x06\x66ields\x18\x06 \x03(\x0b\x32&.dvf.telemetry.v1.LogEntry.FieldsEntry\x12-\n\ttimestamp\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x1a-\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xe4\x01\n\x0bMetricEntry\x12\r\n\x05vm_id\x18\x01 \x01(\t\x12\x10\n\x08\x61gent_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\x01\x12\x39\n\x06labels\x18\x05 \x03(\x0b\x32).dvf.telemetry.v1.MetricEntry.LabelsEntry\x12-\n\ttimestamp\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x81\x01\n\nEventEntry\x12\r\n\x05vm_id\x18\x01 \x01(\t\x12\x10\n\x08\x61gent_id\x18\x02 \x01(\t\x12\x12\n\nevent_type\x18\x03 \x01(\t\x12\x0f\n\x07payload\x18\x04 \x01(\t\x12-\n\ttimestamp\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"3\n\tStreamAck\x12\x16\n\x0ereceived_count\x18\x01 \x01(\x03\x12\x0e\n\x06status\x18\x02 \x01(\t2\xf7\x01\n\x10TelemetryService\x12G\n\nStreamLogs\x12\x1a.dvf.telemetry.v1.LogEntry\x1a\x1b.dvf.telemetry.v1.StreamAck(\x01\x12M\n\rStreamMetrics\x12\x1d.dvf.telemetry.v1.MetricEntry\x1a\x1b.dvf.telemetry.v1.StreamAck(\x01\x12K\n\x0cStreamEvents\x12\x1c.dvf.telemetry.v1.EventEntry\x1a\x1b.dvf.telemetry.v1.StreamAck(\x01\x42UZSgithub.com/kartheekbudime/driver-validation-suite/go-orchestrator/proto/telemetrypbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZSgithub.com/kartheekbudime/driver-validation-suite/go-orchestrator/proto/telemetrypb'
  _globals['_LOGENTRY_FIELDSENTRY']._loaded_options = None
  _globals['_LOGENTRY_FIELDSENTRY']._serialized_options = b'8\001'
  _globals['_METRICENTRY_LABELSENTRY']._loaded_options = None
  _globals['_METRICENTRY_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_LOGENTRY']._serialized_start=71
  _globals['_LOGENTRY']._serialized_end=315
  _globals['_LOGENTRY_FIELDSENTRY']._serialized_start=270
  _globals['_LOGENTRY_FIELDSENTRY']._serialized_end=315
  _globals['_METRICENTRY']._serialized_start=318
  _globals['_METRICENTRY']._serialized_end=546
  _globals['_METRICENTRY_LABELSENTRY']._serialized_start=501
  _globals['_METRICENTRY_LABELSENTRY']._serialized_end=546
  _globals['_EVENTENTRY']._serialized_start=549
  _globals['_EVENTENTRY']._serialized_end=678
  _globals['_STREAMACK']._serialized_start=680
  _globals['_STREAMACK']._serialized_end=731
  _globals['_TELEMETRYSERVICE']._serialized_start=734
  _globals['_TELEMETRYSERVICE']._serialized_end=981
# @@protoc_insertion_point(module_scope)
