# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import telemetry_pb2 as telemetry__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in telemetry_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TelemetryServiceStub:
    """TelemetryService handles real-time telemetry streaming from guest agents.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamLogs = channel.stream_unary(
                '/dvf.telemetry.v1.TelemetryService/StreamLogs',
                request_serializer=telemetry__pb2.LogEntry.SerializeToString,
                response_deserializer=telemetry__pb2.StreamAck.FromString,
                _registered_method=True)
        self.StreamMetrics = channel.stream_unary(
                '/dvf.telemetry.v1.TelemetryService/StreamMetrics',
                request_serializer=telemetry__pb2.MetricEntry.SerializeToString,
                response_deserializer=telemetry__pb2.StreamAck.FromString,
                _registered_method=True)
        self.StreamEvents = channel.stream_unary(
                '/dvf.telemetry.v1.TelemetryService/StreamEvents',
                request_serializer=telemetry__pb2.EventEntry.SerializeToString,
                response_deserializer=telemetry__pb2.StreamAck.FromString,
                _registered_method=True)


class TelemetryServiceServicer:
    """TelemetryService handles real-time telemetry streaming from guest agents.
    """

    def StreamLogs(self, request_iterator, context):
        """StreamLogs receives a stream of log entries from a guest agent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMetrics(self, request_iterator, context):
        """StreamMetrics receives a stream of metric data points from a guest agent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request_iterator, context):
        """StreamEvents receives structured events from a guest agent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TelemetryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamLogs': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamLogs,
                    request_deserializer=telemetry__pb2.LogEntry.FromString,
                    response_serializer=telemetry__pb2.StreamAck.SerializeToString,
            ),
            'StreamMetrics': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamMetrics,
                    request_deserializer=telemetry__pb2.MetricEntry.FromString,
                    response_serializer=telemetry__pb2.StreamAck.SerializeToString,
            ),
            'StreamEvents': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=telemetry__pb2.EventEntry.FromString,
                    response_serializer=telemetry__pb2.StreamAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dvf.telemetry.v1.TelemetryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dvf.telemetry.v1.TelemetryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TelemetryService:
    """TelemetryService handles real-time telemetry streaming from guest agents.
    """

    @staticmethod
    def StreamLogs(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/dvf.telemetry.v1.TelemetryService/StreamLogs',
            telemetry__pb2.LogEntry.SerializeToString,
            telemetry__pb2.StreamAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamMetrics(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/dvf.telemetry.v1.TelemetryService/StreamMetrics',
            telemetry__pb2.MetricEntry.SerializeToString,
            telemetry__pb2.StreamAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/dvf.telemetry.v1.TelemetryService/StreamEvents',
            telemetry__pb2.EventEntry.SerializeToString,
            telemetry__pb2.StreamAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
